[package]
name = "rm"
version = "0.1.0"
authors = ["Gab David <gbianchetdavid@ebsco.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
clap = { version = "^2.33.0", features = ["yaml", "wrap_help"] }

[build-dependencies]
clap = { version = "^2.33.0", features = ["yaml"] }
