[package]
name = "yes"
version = "0.1.0"
authors = ["GrayJack <gr41.j4ck@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
clap = { version = "^2.33.0", features = ["yaml"] }

[build-dependencies]
clap = { version = "^2.33.0", features = ["yaml"] }
