language: rust
rust:
  - 1.36.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - rustup target add x86_64-unknown-netbsd x86_64-unknown-freebsd x86_64-unknown-openbsd x86_64-unknown-dragonflybsd
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo build --verbose --all --target x86_64-unknown-freebsd
  - cargo test --verbose --all --target x86_64-unknown-freebsd
  - cargo build --verbose --all --target x86_64-unknown-netbsd
  - cargo test --verbose --all --target x86_64-unknown-netbsd
  - cargo build --verbose --all --target x86_64-unknown-openbsd
  - cargo test --verbose --all --target x86_64-unknown-openbsd
  - cargo build --verbose --all --target x86_64-unknown-dragonflybsd
  - cargo test --verbose --all --target x86_64-unknown-dragonflybsd
