name: Rust

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.37.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - run: rustup target add x86_64-unknown-freebsd x86_64-unknown-netbsd x86_64-fuchsia x86_64-sun-solaris
    - name: Check Linux
      run: cargo check --verbose
    - name: Check FreeBSD
      run: cargo check --verbose --target x86_64-unknown-freebsd
    - name: Check NetBSD
      run: cargo check --verbose --target x86_64-unknown-netbsd
    - name: Check Fuchsia
      run: cargo check --verbose --target x86_64-fuchsia
    - name: Check Solaris
      run: cargo check --verbose --target x86_64-sun-solaris
    - name: Run tests
      run: cargo test --verbose

  build_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        rust: [1.37.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose

  # check_openbsd:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       rust: [1.37.0, stable, beta, nightly]
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: hecrj/setup-rust-action@v1
  #     with:
  #       rust-version: ${{ matrix.rust }}
  #   - run: rustup target add x86_64-unknown-openbsd
  #   - name: Check OpenBSD
  #     run: cargo check --verbose --target x86_64-unknown-openbsd
